In [1]:
import pandas as pd

In [219]:
df = pd.read_csv('Titanic-Dataset.csv')

In [220]:
df.head()

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,1,0,S,A/5 21171,7.2500,NaN,1,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C,PC 17599,71.2833,C85,2,1,1
2,"Heikkinen, Miss. Laina",female,26.0,0,0,S,STON/O2. 3101282,7.9250,NaN,3,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S,113803,53.1000,C123,4,1,1
4,"Allen, Mr. William Henry",male,35.0,0,0,S,373450,8.0500,NaN,5,3,0

In [8]:
df[(df['Pclass'] == 3) & (df['Sex'] == 'female') & (df['Age'] > 30)][['Name', 'Age', 'Fare']].sort_values('Age', ascending=False)

                                                  Name   Age     Fare
483                             Turkula, Mrs. (Hedwig)  63.0   9.5875
736            Ford, Mrs. Edward (Margaret Ann Watson)  48.0  34.3750
132     Robins, Mrs. Alexander A (Grace Charity Laury)  47.0  14.5000
167    Skoog, Mrs. William (Anna Bernhardina Karlsson)  45.0  27.9000
276                  Lindblom, Miss. Augusta Charlotta  45.0   7.7500
362                    Barbara, Mrs. (Catherine David)  45.0  14.4542
678            Goodwin, Mrs. Frederick (Augusta Tyler)  43.0  46.9000
638             Panula, Mrs. Juha (Maria Emilia Ojala)  41.0  39.6875
254           Rosblom, Mrs. Viktor (Helena Wilhelmina)  41.0  20.2125
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  40.0   9.4750
610  Andersson, Mrs. Anders Johan (Alfrida Konstant...  39.0  31.2750
885               Rice, Mrs. William (Margaret Norton)  39.0  29.1250
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0  31.3875
503                     Laitinen, Miss. Kristina Sofia  37.0   9.5875
559       de Messemaeker, Mrs. Guillaume Joseph (Emma)  36.0  17.4000
279                   Abbott, Mrs. Stanton (Rosa Hunt)  35.0  20.2500
85   Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  33.0  15.8500
657                      Bourke, Mrs. John (Catherine)  32.0  15.5000
797                                   Osman, Mrs. Mara  31.0   8.6833
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0  18.0000
328     Goldsmith, Mrs. Frank John (Emily Alice Brown)  31.0  20.5250
396                                Olsson, Miss. Elina  31.0   7.8542
767                                 Mangan, Miss. Mary  30.5   7.7500

In [15]:
df.groupby('Embarked', dropna=False)['Embarked'].count()

Embarked
C      168
Q       77
S      644
NaN      0
Name: Embarked, dtype: int64

In [17]:
df.groupby('Embarked', dropna=False).count()

,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,PassengerId,Pclass,Survived
Embarked,,,,,,,,,,,
C,168,168,130,168,168,168,168,69,168,168,168
Q,77,77,28,77,77,77,77,4,77,77,77
S,644,644,554,644,644,644,644,129,644,644,644
NaN,2,2,2,2,2,2,2,2,2,2,2

In [21]:
df.groupby('Pclass')['Survived'].mean().mul(100).sort_values(ascending=False)

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [27]:
df[(df['Age'].isna()) & (~df['Cabin'].isna())][['Name', 'Pclass', 'Cabin']]

                                                  Name  Pclass  Cabin
31      Spencer, Mrs. William Augustus (Marie Eugenie)       1    B78
55                                   Woolner, Mr. Hugh       1    C52
128                                  Peter, Miss. Anna       3  F E69
166             Chibnall, Mrs. (Edith Martha Bowerman)       1    E33
185                              Rood, Mr. Hugh Roscoe       1    A32
284                         Smith, Mr. Richard William       1    A19
298                              Saalfeld, Mr. Adolphe       1   C106
303                                Keane, Miss. Nora A       2   E101
351             Williams-Lambert, Mr. Fletcher Fellows       1   C128
457                  Kenyon, Mrs. Frederick R (Marion)       1    D21
475                        Clifford, Mr. George Quincy       1    A14
527                                 Farthing, Mr. John       1    C95
669  Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)       1   C126
711                                 Klaber, Mr. Herman       1   C124
740                        Hawksford, Mr. Walter James       1    D45
776                                   Tobin, Mr. Roger       3    F38
815                                   Fry, Mr. Richard       1   B102
839                               Marechal, Mr. Pierre       1    C47
849       Goldenberg, Mrs. Samuel L (Edwiga Grabowska)       1    C92

In [28]:
df.groupby(['Sex', 'Pclass']).agg(passengerC=('PassengerId', 'size'),
                                 medianA=('Age', 'median'), 
                                 meanFare=('Fare', 'mean'))

               passengerC  medianA    meanFare
Sex    Pclass
female 1               94     35.0  106.125798
       2               76     28.0   21.970121
       3              144     21.5   16.118810
male   1              122     40.0   67.226127
       2              108     30.0   19.741782
       3              347     25.0   12.661633

In [33]:
df.loc[df.groupby('Pclass')['Fare'].idxmin(), ['Pclass', 'Name', 'Fare']]

     Pclass                         Name  Fare
263       1        Harrison, Mr. William   0.0
277       2  Parkes, Mr. Francis "Frank"   0.0
179       3          Leonard, Mr. Lionel   0.0

In [46]:
Female = df[(df['Sex'] == 'female') & (df['Survived'] == 1)]

In [47]:
df.loc[Female.groupby('Pclass')['Age'].idxmax(), ['Pclass', 'Name', 'Age']]

     Pclass                               Name   Age
275       1  Andrews, Miss. Kornelia Theodosia  63.0
15        2   Hewlett, Mrs. (Mary D Kingcome)   55.0
483       3             Turkula, Mrs. (Hedwig)  63.0

In [51]:
missingAge = df[df['Age'].isna()]

In [61]:
missingAge['Age'] = missingAge['Age'].fillna(1)

In [71]:
df.groupby('Pclass', dropna=False)['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [65]:
missingAge.groupby('Pclass').agg(ageM=('Age', 'mean'))

        ageM
Pclass
1        1.0
2        1.0
3        1.0

In [77]:
df[(df['SibSp'] == 0) & (df['Parch'] == 0)][['Name', 'Pclass', 'Survived']]

                             Name  Pclass  Survived
2          Heikkinen, Miss. Laina       3         1
4        Allen, Mr. William Henry       3         0
5                Moran, Mr. James       3         0
6         McCarthy, Mr. Timothy J       1         0
11       Bonnell, Miss. Elizabeth       1         1
..                            ...     ...       ...
884        Sutehall, Mr. Henry Jr       3         0
886         Montvila, Rev. Juozas       2         0
887  Graham, Miss. Margaret Edith       1         1
889         Behr, Mr. Karl Howell       1         1
890           Dooley, Mr. Patrick       3         0

[537 rows x 3 columns]

In [80]:
(df.groupby('Embarked').agg(passC=('PassengerId', 'size'),
                          survival=('Survived', 'mean')).assign(survival=lambda x: x['survival'] * 100).query('passC >= 100')
.sort_values('survival', ascending=False))

          passC   survival
Embarked
C           168  55.357143
S           644  33.695652

In [251]:
df2 = df.copy()

In [169]:
df2['classMedianFare'] = df2.groupby('Pclass')['Fare'].transform('median')

In [170]:
df2[['Name', 'Pclass', 'Fare', 'classMedianFare']].head(10)

,Name,Pclass,Fare,classMedianFare
0,"Braund, Mr. Owen Harris",3,7.2500,8.0500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,71.2833,60.2875
2,"Heikkinen, Miss. Laina",3,7.9250,8.0500
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,53.1000,60.2875
4,"Allen, Mr. William Henry",3,8.0500,8.0500
5,"Moran, Mr. James",3,8.4583,8.0500
6,"McCarthy, Mr. Timothy J",1,51.8625,60.2875
7,"Palsson, Master. Gosta Leonard",3,21.0750,8.0500
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",3,11.1333,8.0500
9,"Nasser, Mrs. Nicholas (Adele Achem)",2,30.0708,14.2500

In [171]:
df2.loc[df2['Fare']/2 > df2['classMedianFare'],['Name', 'Fare', 'Pclass', 'classMedianFare']]

,Name,Fare,Pclass,classMedianFare
7,"Palsson, Master. Gosta Leonard",21.0750,3,8.0500
9,"Nasser, Mrs. Nicholas (Adele Achem)",30.0708,2,14.2500
10,"Sandstrom, Miss. Marguerite Rut",16.7000,3,8.0500
13,"Andersson, Mr. Anders Johan",31.2750,3,8.0500
16,"Rice, Master. Eugene",29.1250,3,8.0500
...,...,...,...,...
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",164.8667,1,60.2875
858,"Baclini, Mrs. Solomon (Latifa Qurban)",19.2583,3,8.0500
863,"Sage, Miss. Dorothy Edith ""Dolly""",69.5500,3,8.0500
885,"Rice, Mrs. William (Margaret Norton)",29.1250,3,8.0500
888,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,3,8.0500

In [172]:
df2['medianAge'] = df2.groupby(['Sex', 'Pclass'])['Age'].transform('median')

In [173]:
df2.loc[(df2['Age'] + 15) > df2['medianAge']].head(10)

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived,classMedianFare,medianAge
0,"Braund, Mr. Owen Harris",male,22.0,1,0,S,A/5 21171,7.2500,NaN,1,3,0,8.0500,25.0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C,PC 17599,71.2833,C85,2,1,1,60.2875,35.0
2,"Heikkinen, Miss. Laina",female,26.0,0,0,S,STON/O2. 3101282,7.9250,NaN,3,3,1,8.0500,21.5
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S,113803,53.1000,C123,4,1,1,60.2875,35.0
4,"Allen, Mr. William Henry",male,35.0,0,0,S,373450,8.0500,NaN,5,3,0,8.0500,25.0
6,"McCarthy, Mr. Timothy J",male,54.0,0,0,S,17463,51.8625,E46,7,1,0,60.2875,40.0
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,S,347742,11.1333,NaN,9,3,1,8.0500,21.5
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,C,237736,30.0708,NaN,10,2,1,14.2500,28.0
11,"Bonnell, Miss. Elizabeth",female,58.0,0,0,S,113783,26.5500,C103,12,1,1,60.2875,35.0
12,"Saundercock, Mr. William Henry",male,20.0,0,0,S,A/5. 2151,8.0500,NaN,13,3,0,8.0500,25.0

In [179]:
medAge = df2.groupby(['Sex', 'Pclass'])['Age'].transform('median')

In [180]:
Ogmissing = df2.loc[df2['Age'].isna()]

In [182]:
Ogmissing['Age'] = Ogmissing['Age'].fillna(medAge)

In [184]:
Ogmissing.head(10)

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived,classMedianFare,medianAge
5,"Moran, Mr. James",male,25.0,0,0,Q,330877,8.4583,NaN,6,3,0,8.0500,25.0
17,"Williams, Mr. Charles Eugene",male,30.0,0,0,S,244373,13.0000,NaN,18,2,1,14.2500,30.0
19,"Masselmani, Mrs. Fatima",female,21.5,0,0,C,2649,7.2250,NaN,20,3,1,8.0500,21.5
26,"Emir, Mr. Farred Chehab",male,25.0,0,0,C,2631,7.2250,NaN,27,3,0,8.0500,25.0
28,"O'Dwyer, Miss. Ellen ""Nellie""",female,21.5,0,0,Q,330959,7.8792,NaN,29,3,1,8.0500,21.5
29,"Todoroff, Mr. Lalio",male,25.0,0,0,S,349216,7.8958,NaN,30,3,0,8.0500,25.0
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,35.0,1,0,C,PC 17569,146.5208,B78,32,1,1,60.2875,35.0
32,"Glynn, Miss. Mary Agatha",female,21.5,0,0,Q,335677,7.7500,NaN,33,3,1,8.0500,21.5
36,"Mamee, Mr. Hanna",male,25.0,0,0,C,2677,7.2292,NaN,37,3,1,8.0500,25.0
42,"Kraeff, Mr. Theodor",male,25.0,0,0,C,349253,7.8958,NaN,43,3,0,8.0500,25.0

In [186]:
(df2.groupby(['Pclass', 'Sex']).agg(sur=('Survived', 'mean')).assign(sur= lambda x: x['sur'] * 100)
    .unstack('Sex'))

              sur
Sex        female       male
Pclass
1       96.808511  36.885246
2       92.105263  15.740741
3       50.000000  13.544669

In [208]:
df2.loc[df2.groupby('Pclass')['Fare'].idxmax()]

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived,classMedianFare,medianAge
258,"Ward, Miss. Anna",female,35.0,0,0,C,PC 17755,512.3292,NaN,259,1,1,60.2875,35.0
72,"Hood, Mr. Ambrose Jr",male,21.0,0,0,S,S.O.C. 14879,73.5000,NaN,73,2,0,14.2500,30.0
159,"Sage, Master. Thomas Henry",male,NaN,8,2,S,CA. 2343,69.5500,NaN,160,3,0,8.0500,25.0

In [215]:
df2.loc[(df2['Fare'] == 512.3292) | (df2['Fare'] == 73.5000) | (df2['Fare'] == 69.5500), ['Pclass', 'Name', 'Fare']]

     Pclass                                Name      Fare
72        2                Hood, Mr. Ambrose Jr   73.5000
120       2         Hickman, Mr. Stanley George   73.5000
159       3          Sage, Master. Thomas Henry   69.5500
180       3        Sage, Miss. Constance Gladys   69.5500
201       3                 Sage, Mr. Frederick   69.5500
258       1                    Ward, Miss. Anna  512.3292
324       3            Sage, Mr. George John Jr   69.5500
385       2           Davies, Mr. Charles Henry   73.5000
655       2           Hickman, Mr. Leonard Mark   73.5000
665       2                  Hickman, Mr. Lewis   73.5000
679       1  Cardeza, Mr. Thomas Drake Martinez  512.3292
737       1              Lesurer, Mr. Gustave J  512.3292
792       3             Sage, Miss. Stella Anna   69.5500
846       3            Sage, Mr. Douglas Bullen   69.5500
863       3   Sage, Miss. Dorothy Edith "Dolly"   69.5500

In [222]:
df2['GSurvivalPer'] = df2.groupby(['Sex', 'Pclass'])['Survived'].transform('mean').mul(100)

In [224]:
df2.loc[df2['GSurvivalPer'] > 50]

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived,classMedianFare,medianAge,GSurvivalPer
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,C,PC 17599,71.2833,C85,2,1,1,60.2875,35.0,96.808511
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,S,113803,53.1000,C123,4,1,1,60.2875,35.0,96.808511
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,C,237736,30.0708,NaN,10,2,1,14.2500,28.0,92.105263
11,"Bonnell, Miss. Elizabeth",female,58.0,0,0,S,113783,26.5500,C103,12,1,1,60.2875,35.0,96.808511
15,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,S,248706,16.0000,NaN,16,2,1,14.2500,28.0,92.105263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,S,11751,52.5542,D35,872,1,1,60.2875,35.0,96.808511
874,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,C,P/PP 3381,24.0000,NaN,875,2,1,14.2500,28.0,92.105263
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,C,11767,83.1583,C50,880,1,1,60.2875,35.0,96.808511
880,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,S,230433,26.0000,NaN,881,2,1,14.2500,28.0,92.105263
887,"Graham, Miss. Margaret Edith",female,19.0,0,0,S,112053,30.0000,B42,888,1,1,60.2875,35.0,96.808511

In [234]:
df2.groupby('Pclass')['Fare'].value_counts()

Pclass  Fare
1       26.5500    15
        52.0000     7
        0.0000      5
        30.0000     5
        30.5000     5
                   ..
3       9.8458      1
        7.1417      1
        9.2167      1
        7.3125      1
        10.5167     1
Name: count, Length: 255, dtype: int64

In [254]:
surv = df2.loc[df2['Survived'] == 0 ]

In [255]:
notsurv = df2.loc[df2['Survived'] == 1]

In [267]:
MFsurv = surv.groupby('Pclass').agg(mean1=('Fare', 'mean'))

In [268]:
MFnotsurv = notsurv.groupby('Pclass').agg(mean2=('Fare', 'mean'))

In [270]:
MFnotsurv - MFsurv

        mean1  mean2
Pclass
1         NaN    NaN
2         NaN    NaN
3         NaN    NaN

In [271]:
df2['familySize'] = df2['SibSp'] + df2['Parch'] + 1

In [273]:
(df2.groupby('familySize').agg(passCount=('PassengerId', 'size'),
                             survival=('Survived', 'mean'))
    .assign(survival=lambda x: x['survival'] * 100))

            passCount   survival
familySize
1                 537  30.353818
2                 161  55.279503
3                 102  57.843137
4                  29  72.413793
5                  15  20.000000
6                  22  13.636364
7                  12  33.333333
8                   6   0.000000
11                  7   0.000000

In [280]:
df2['familyType'] = pd.cut(df2['familySize'], bins= [1, 2, 5, float('inf')], labels= ['Alone', 'Small', 'Large'],
                          right=False )

In [279]:
df2.groupby('familyType').agg(PasssC=('PassengerId', 'size'), 
                             survivPer=('Survived', 'mean')).assign(survivPer= lambda x: x['survivPer'] * 100)

            PasssC  survivPer
familyType
Alone          537  30.353818
Small          292  57.876712
Large           62  16.129032

In [282]:
df2['AgeBrand'] = pd.cut(df2['Age'], bins=[0,18,40,60,float('inf')], labels=['0-18','18-39','40-59','60+'],
                         right=False)

In [284]:
df2.groupby(['AgeBrand', 'Pclass']).agg(survivalPer=('Survived', 'mean')
                                       ).assign(survivalPer=lambda x: x['survivalPer'] * 100).unstack()

         survivalPer
Pclass             1          2          3
AgeBrand
0-18       91.666667  91.304348  37.179487
18-39      74.193548  40.707965  22.844828
40-59      57.812500  45.454545   5.000000
60+        29.411765  25.000000  20.000000

In [285]:
df2['Name'].head(3)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: str

In [300]:
df2['Title'] = df2['Name'].str.split(',').str[1].str.split('.').str[0].str.strip()

In [301]:
df2['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [308]:
df2['Title'].apply(lambda x: 'Rare' if  < 10 else x)

NameError: name 'count' is not defined