## Logistical Regression Model

### Import Tools

In [54]:
import pandas as pd #pandas -> data cleaning, feature engineering 
from sklearn.linear_model import LogisticRegression #for our model
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix #for evaluation on the model 
from sklearn.model_selection import train_test_split #to group the data eg. training, testing
from matplotlib import pyplot as plt # for visualization

In [55]:
df = pd.read_csv('Titanic-Dataset.csv') #we import the data locally and name it df

### Split the Data

In [4]:
X = df[['Pclass', 'Sex', 'Age', 'Fare']].copy()#the columns we'll be using for our first training set
X['Sex'] = X['Sex'].map({'male':0, 'female':1})#encode the sex column
y = df['Survived'] #what we hope to perdict

In [5]:
X.isna().sum() #checking for missing values

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, #varibles to target 
    test_size=0.2, #the batching
    random_state=42, #randomly produce the same split every time 
    stratify= y #keeps approximately the same survival/non-survival proportions in both sets  
)

In [7]:
median = X_train['Age'].median()#find the median set for both training and testing set
median2 = X_test['Age'].median()

In [8]:
X_train['Age'] = X_train['Age'].fillna(median)# fill in for missing aga values 
X_test['Age'] = X_test['Age'].fillna(median)

In [9]:
print(X_train.isna().sum())# check
print(X_test.isna().sum())

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64
Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

### Create a Baseline
This let's us tell if our survived and not survived are of equal sample numbers in the dataset or which one is more

In [10]:
baselineClass = y_train.mode()[0]#this tells us that 'did not survive' is more common in our data

baselineAccuracy = (y_test == baselineClass).mean() * 100

baselineClass, baselineAccuracy

(np.int64(0), np.float64(61.452513966480446))

In [11]:
model = LogisticRegression(max_iter=1000)

In [12]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [13]:
modelAccuracy = model.score(X_test, y_test) * 100

In [14]:
[[ baselineAccuracy, modelAccuracy ]]

[[np.float64(61.452513966480446), 78.77094972067039]]

In [15]:
yPred = model.predict(X_test)

In [16]:
yPred[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [17]:
[[ yPred[:10], y_test[:10]]]

[[array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0]),
  565    0
  160    0
  553    1
  860    0
  241    1
  559    1
  387    1
  536    0
  698    0
  99     0
  Name: Survived, dtype: int64]]

In [18]:
confusionMatrix = confusion_matrix(y_test, yPred)
confusionMatrix

array([[94, 16],
       [22, 47]])

# Precision and Recall

In [24]:
 print(classification_report(y_test,yPred))

              precision    recall  f1-score   support

           0       0.81      0.85      0.83       110
           1       0.75      0.68      0.71        69

    accuracy                           0.79       179
   macro avg       0.78      0.77      0.77       179
weighted avg       0.79      0.79      0.79       179

In [19]:
yProb = model.predict_proba(X_test)[:, 1]
yProb[:10]

array([0.10596377, 0.0561998 , 0.11033039, 0.06168765, 0.55295579,
       0.49025717, 0.7450901 , 0.35293448, 0.34759057, 0.20560858])

In [20]:
yPred3 = (yProb >= 0.3).astype(int)
print(classification_report(y_test, yPred3))

              precision    recall  f1-score   support

           0       0.86      0.73      0.79       110
           1       0.65      0.81      0.72        69

    accuracy                           0.76       179
   macro avg       0.76      0.77      0.76       179
weighted avg       0.78      0.76      0.76       179

In [22]:
yPred7 = (yProb >= 0.7).astype(int)
print(classification_report(y_test, yPred7))

              precision    recall  f1-score   support

           0       0.74      0.96      0.83       110
           1       0.89      0.45      0.60        69

    accuracy                           0.77       179
   macro avg       0.81      0.71      0.72       179
weighted avg       0.79      0.77      0.74       179

In [25]:
X_train.shape

(712, 4)

In [26]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 692 to 507
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  712 non-null    int64
 1   Sex     712 non-null    int64
 2   Age     712 non-null    float64
 3   Fare    712 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 27.8 KB

In [28]:
X_train.isna().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [66]:
dfff = df.loc[X_train.index].copy()

In [67]:
dfff['familySize'] = dfff['SibSp'] + dfff['Parch'] + 1

In [68]:
summary = (dfff.groupby('familySize').agg(PassengerCount=('PassengerId', 'size'),
                               survivalPer=('Survived', 'mean')).assign(survivalPer= lambda x: x['survivalPer'] * 100)
    .sort_values('familySize'))

In [69]:
dfff

,Name,Sex,Age,SibSp,Parch,Embarked,Ticket,Fare,Cabin,PassengerId,Pclass,Survived,familySize
692,"Lam, Mr. Ali",male,NaN,0,0,S,1601,56.4958,NaN,693,3,1,1
481,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,S,239854,0.0000,NaN,482,2,0,1
527,"Farthing, Mr. John",male,NaN,0,0,S,PC 17483,221.7792,C95,528,1,0,1
855,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,S,392091,9.3500,NaN,856,3,1,2
801,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.0,1,1,S,C.A. 31921,26.2500,NaN,802,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,Q,330980,7.8792,NaN,360,3,1,1
258,"Ward, Miss. Anna",female,35.0,0,0,C,PC 17755,512.3292,NaN,259,1,1,1
736,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,S,W./C. 6608,34.3750,NaN,737,3,0,5
462,"Gee, Mr. Arthur H",male,47.0,0,0,S,111320,38.5000,E63,463,1,0,1
507,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,S,111427,26.5500,NaN,508,1,1,1

In [70]:
summary

            PassengerCount  survivalPer
familySize
1                      434    29.953917
2                      129    55.038760
3                       77    62.337662
4                       22    72.727273
5                       14    21.428571
6                       16     6.250000
7                       11    36.363636
8                        4     0.000000
11                       5     0.000000

In [74]:
dfff['IsAlone'] = dfff['familySize'] == 1

In [77]:
dfff['IsAlone'] = dfff['IsAlone'].map({True:1, False:0})

In [79]:
dfff[['familySize', 'IsAlone']].head(5)

     familySize  IsAlone
692           1        1
481           1        1
527           1        1
855           2        0
801           3        0

In [80]:
X_trainNew = X_train.copy()
X_trainNew['IsAlone'] = dfff['IsAlone']

In [82]:
X_trainNew.head(5)

     Pclass  Sex   Age      Fare  IsAlone
692       3    0  28.5   56.4958        1
481       2    0  28.5    0.0000        1
527       1    0  28.5  221.7792        1
855       3    1  18.0    9.3500        0
801       2    1  31.0   26.2500        0

In [83]:
X_trainNew.shape

(712, 5)